
// This file has been generated by the GUI designer. Do not modify.
namespace LadderLogic
{
	public sealed partial class MainWindow
	{
		private void Build ()
		{
			Stetic.Gui.Initialize (this);
			// Widget LadderLogic.MainWindow
			Name = "LadderLogic.MainWindow";
			Title = Mono.Unix.Catalog.GetString ("MainWindow");
			WindowPosition = ((Gtk.WindowPosition)(4));
			if ((Child != null)) {
				Child.ShowAll ();
			}
			DefaultWidth = 400;
			DefaultHeight = 300;
			Show ();
		}
	}
}
